build:
    docker-compose build

up:
    docker-compose up -d

down:
    docker-compose down

restart:
    docker-compose restart

logs:
    docker-compose logs -f

.PHONY: build up down restart logs
